
#/etc/X11/xorg.conf.d

Section "InputClass"
    Identifier "ELAN1203 Touchpad"
    MatchProduct "ELAN1203:00 04F3:307A Touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"

    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "TappingButtonMap" "lrm"
    Option "NaturalScrolling" "true"
    Option "ClickMethod" "clickfinger"
    Option "TappingDragLock" "true"
    Option "MiddleEmulation" "true"
EndSection

Section "InputClass"
    Identifier "ELAN1203 Mouse"
    MatchProduct "ELAN1203:00 04F3:307A Mouse"
    Driver "libinput"
    Option "Ignore" "true"
EndSection
