alias aura="~/.local/bin/aura"
alias battery="~/.local/bin/battery"
alias clipin="~/.local/bin/clipin"
alias clipout="~/.local/bin/clipout"
alias dwpower="~/.local/bin/dwpower"
alias music="~/.local/bin/music"
alias newlook="~/.local/bin/newlook"
alias record="~/.local/bin/record"
alias mpv='mpv --no-osc'
