#/boot/loader/entries/2025-08-13_19-04-28_linux.conf

# Created by: archinstall
# Created on: 2025-08-13_19-04-28
title   Arch Linux (linux)
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=PARTUUID=3d1a4ffa-7a9a-4d42-a7ee-0adfbfaf84b2 zswap.enabled=0 rw rootfstype=ext4 nvidia-drm.modeset=1
